# Generated by Django 2.0.7 on 2018-07-11 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='billingAddress',
            new_name='billingName',
        ),
    ]
